# Required packages
# install.packages(c("ncdf4", "tools"))
library(ncdf4)
library(tools)

# ---- Helper: safely set a global attribute ----
nc_put_att_global <- function(nc, name, value) {
  # ncatt_put uses varid = 0 for globals
  ncatt_put(nc, varid = 0, attname = name, attval = value)
}

# ---- Helper: safely set variable attributes if variable exists ----
nc_put_att_var <- function(nc, varname, attname, attval) {
  if (!varname %in% names(nc$var)) {
    warning(sprintf("Variable '%s' not found; skipping attribute '%s'.", varname, attname))
    return(invisible(FALSE))
  }
  ncatt_put(nc, varid = varname, attname = attname, attval = attval)
  invisible(TRUE)
}

# ---- Main: annotate a WetLSP phenometrics NetCDF ----
annotate_wetlsp_netcdf <- function(
    nc_path,
    out_path = NULL,
    site_id = NULL,
    year = NULL,
    creator_email = NULL,
    pipeline_version = NULL,
    years_included = "2020–2025",
    license = "CC-BY-4.0"
) {
  stopifnot(file.exists(nc_path))
  
  if (is.null(out_path)) {
    # default: create sibling file with suffix
    out_path <- file.path(dirname(nc_path),
                          paste0(file_path_sans_ext(basename(site_dir)), "-lsp-", year, ".nc"))
  }
  
  # Copy file (safer than trying to mutate in place)
  ok <- file.copy(nc_path, out_path, overwrite = TRUE)
  if (!ok) stop("Failed to copy NetCDF to out_path. Check permissions.")
  
  nc <- nc_open(out_path, write = TRUE)
  on.exit(nc_close(nc), add = TRUE)
  
  # ---- Infer site/year if not provided ----
  if (is.null(site_id)) {
    # Try to infer from filename like wetlsp_2024.nc or US-Myb_2024.nc
    site_id <- NA_character_
  }
  if (is.null(year)) {
    year <- NA_character_
  }
  
  # ---- Global attributes (CF + provenance) ----
  title <- sprintf("LSP phenometrics for site %s (%s)", site_id %||% "<SITEID>", year %||% "<YEAR>")
  summary <- paste0(
    "This dataset contains spatial phenometrics derived from PlanetScope surface reflectance imagery ",
    "for the Nachusa Grasslands site ", (site_id %||% "<SITEID>"), ". ",
    "Variables represent phenological metrics computed from EVI time series (including up to two seasonal cycles where supported). ",
    "The NetCDF is a phenometrics-only product and does not include a time dimension; ",
    "raw and gap-filled EVI time series and per-pixel diagnostic outputs are distributed separately as companion artifacts."
  )
  
  # history string with optional pipeline_version
  hist <- sprintf(
    "Annotated %s. Generated by nachusaLSP processing pipeline%s. Inputs: mosaicked clipped PlanetScope SR scenes (%s). Outputs: per-year phenometrics rasters written to NetCDF with CF-style projection variable (transverse_mercator) and x/y coordinates in meters.",
    format(Sys.Date(), "%Y-%m-%d"),
    if (!is.null(pipeline_version)) paste0(" (version ", pipeline_version, ")") else "",
    years_included
  )
  
  refs <- paste(
    "Moon, M. et al. (2022) Scientific Data: phenometrics from PlanetScope (Wetland Land Surface Phenology). https://doi.org/10.1038/s41597-022-01570-5",
    "Moon, M. et al. (2023) ORNL DAAC Land Surface Phenology, Eddy Covariance Tower Sites, North America, 2017-2021,  https://doi.org/10.3334/ORNLDAAC/2033",
    "PlanetScope imagery © Planet Labs PBC.",
    "LSP pipeline documentation and code: <URL/DOI when available>."
  )
  
  keywords <- paste(
    "PlanetScope; EVI; phenology; phenometrics; wetlands; eddy covariance; AmeriFlux; remote sensing; time series; WetLSP",
    sep = ""
  )
  
  # Write globals
  nc_put_att_global(nc, "title", title)
  nc_put_att_global(nc, "summary", summary)
  nc_put_att_global(nc, "Conventions", "CF-1.8")
  nc_put_att_global(nc, "institution", "University of Illinois Chicago (UIC), Department of Earth and Environmental Sciences")
  nc_put_att_global(nc, "creator_name", "Gavin McNicol")
  if (!is.null(creator_email)) nc_put_att_global(nc, "creator_email", creator_email)
  nc_put_att_global(nc, "source", "PlanetScope Surface Reflectance imagery processed with nachusaLSP phenometrics pipeline")
  nc_put_att_global(nc, "history", hist)
  nc_put_att_global(nc, "references", refs)
  nc_put_att_global(nc, "license", license)
  nc_put_att_global(nc, "keywords", keywords)
  nc_put_att_global(nc, "comment", "This file contains phenometrics only (no time dimension). Companion time-series artifacts are distributed separately.")
  
  # ---- Variable attributes: recommended map ----
  # Define a minimal metadata table for your variables.
  # Units here are *placeholders* where the community is inconsistent; adjust if you have canonical definitions.
  var_meta <- list(
    NumCycles = list(long_name = "Number of seasonal cycles detected", units = "1"),
    OGI       = list(long_name = "Onset of greenness increase (cycle 1)", units = "day_of_year"),
    `50PCGI`  = list(long_name = "Date when greenness reaches 50% of amplitude on rising limb (cycle 1)", units = "day_of_year"),
    OGMx      = list(long_name = "Date of maximum greenness (cycle 1)", units = "day_of_year"),
    Peak      = list(long_name = "Peak date (cycle 1)", units = "day_of_year"),
    OGD       = list(long_name = "Onset of greenness decrease (cycle 1)", units = "day_of_year"),
    `50PCGD`  = list(long_name = "Date when greenness declines to 50% of amplitude on falling limb (cycle 1)", units = "day_of_year"),
    OGMn      = list(long_name = "Date of minimum greenness (cycle 1)", units = "day_of_year"),
    EVImax    = list(long_name = "Maximum EVI (cycle 1)", units = "1"),
    EVIamp    = list(long_name = "EVI amplitude (cycle 1)", units = "1"),
    EVIarea   = list(long_name = "Integrated EVI area (cycle 1)", units = "1"),
    QA        = list(long_name = "Quality flag for phenometrics (cycle 1)", units = "1"),
    
    OGI_2     = list(long_name = "Onset of greenness increase (cycle 2)", units = "day_of_year"),
    `50PCGI_2`= list(long_name = "Date when greenness reaches 50% of amplitude on rising limb (cycle 2)", units = "day_of_year"),
    OGMx_2    = list(long_name = "Date of maximum greenness (cycle 2)", units = "day_of_year"),
    Peak_2    = list(long_name = "Peak date (cycle 2)", units = "day_of_year"),
    OGD_2     = list(long_name = "Onset of greenness decrease (cycle 2)", units = "day_of_year"),
    `50PCGD_2`= list(long_name = "Date when greenness declines to 50% of amplitude on falling limb (cycle 2)", units = "day_of_year"),
    OGMn_2    = list(long_name = "Date of minimum greenness (cycle 2)", units = "day_of_year"),
    EVImax_2  = list(long_name = "Maximum EVI (cycle 2)", units = "1"),
    EVIamp_2  = list(long_name = "EVI amplitude (cycle 2)", units = "1"),
    EVIarea_2 = list(long_name = "Integrated EVI area (cycle 2)", units = "1"),
    QA_2      = list(long_name = "Quality flag for phenometrics (cycle 2)", units = "1"),
    
    numObs    = list(long_name = "Number of observations used", units = "1")
  )
  
  # Add FillValue if you know it; otherwise skip to avoid lying.
  # You can detect an existing fill from one variable and standardize later.
  for (v in names(var_meta)) {
    if (v %in% names(nc$var)) {
      nc_put_att_var(nc, v, "long_name", var_meta[[v]]$long_name)
      nc_put_att_var(nc, v, "units", var_meta[[v]]$units)
      # Recommend adding a short description pointing to Moon et al.
      nc_put_att_var(nc, v, "description", "Phenological metric derived from EVI time series; see Moon et al. (2022) Scientific Data for definitions. https://doi.org/10.1038/s41597-022-01570-5")
    }
  }
  
  # Ensure x/y have standard_name if present
  if ("x" %in% names(nc$dim)) {
    # x and y may be dimvars (your print shows they are dimvars)
    if ("x" %in% names(nc$var)) {
      nc_put_att_var(nc, "x", "standard_name", "projection_x_coordinate")
      nc_put_att_var(nc, "x", "long_name", "x coordinate of projection")
      nc_put_att_var(nc, "x", "units", "m")
    }
    if ("y" %in% names(nc$var)) {
      nc_put_att_var(nc, "y", "standard_name", "projection_y_coordinate")
      nc_put_att_var(nc, "y", "long_name", "y coordinate of projection")
      nc_put_att_var(nc, "y", "units", "m")
    }
  }
  
  message("Annotated NetCDF written: ", out_path)
  invisible(out_path)
}

# Small utility: null-coalescing
`%||%` <- function(x, y) if (is.null(x) || (length(x) == 1 && is.na(x))) y else x